version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      POSTGRES_DB: express-graphql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #MYSQL_USER: root
      #MYSQL_PASSWORD: password
      #MYSQL_HOST: mysql
      #MYSQL_DATABASE: prisma
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: prisma
#    ports:
#      - '3306:3306'
#    networks:
#      - backend
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=express-graphql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    # options to maybe speed up postgresql tests.
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
#  data:
#    driver: local
